ansible_ssh_pass: "changeme"
ansible_become_pass: "changeme"

_gluster:
  cluster_name: gluster-jak-kr
  domain: "jtest.pivotal.io"
  major_version: "11"
  minor_version: "17"
  patch_version: "0"
  build_version: ""
  release_date: ""
  repo_url: ""
  download_url: ""
  download: false
  base_path: /root
  host_num: "{{ groups['all'] | length }}"
  local_home_dir: "/home/jomoon"
  dns: "192.168.2.199 8.8.8.8 168.126.63.1"
  download_client: false
  volumes:
    - { dev: "/dev/vdb", dir: "/glusterfs01", vg: "jvg01", lv: "jlv01" }
    - { dev: "/dev/vdc", dir: "/glusterfs02", vg: "jvg02", lv: "jlv02" }
    - { dev: "/dev/vdd", dir: "/glusterfs03", vg: "jvg03", lv: "jlv03" }
  net:
    type: "virtual"                           # Or Physical
    gateway: "192.168.2.1"
    vipaddr: "192.168.1.79"
    ipaddr0: "192.168.0.17"
    ipaddr1: "192.168.1.17"
    ipaddr2: "192.168.2.17"
  client:
    net:
      type: "virtual"                         # Or Physical
      cores: 1
      ipaddr0: "192.168.0.17"
      ipaddr1: "192.168.1.17"
      ipaddr2: "192.168.2.17"
  ext_storage:
    net:
      ipaddr0: "192.168.0."
      ipaddr1: "192.168.1."
      ipaddr2: "192.168.2."
  engine:
    auth:
      url: "https://co9-node01.jtest.pivotal.io/ovirt-engine/api"
      hostname: "co9-node01.jtest.pivotal.io"
      username: "admin@ovirt@internalsso"
      password: "changeme"
      insecure: "true"
  vms:
    rk9: [ "rk9-freeipa", "rk9-node01", "rk9-node02", "rk9-node03", "rk9-node04", "rk9-node05", "rk9-node06", "rk9-node07" ]
    co9: [ "rk9-freeipa", "co9-node01", "co9-node02", "co9-node03", "co9-node04", "co9-node05", "co9-node06", "co9-node07", "co9-node08" ]
    ubt24: [ "rk9-freeipa", "ubt24-node01", "ubt24-node02", "ubt24-node03", "ubt24-node04", "ubt24-node05" ]


_vmware:
  esxi_hostname: "192.168.0.231"
  esxi_username: "root"
  esxi_password: "Changeme34#$"


_kvm:
  hostname: "192.168.0.101"
  username: "root"
  password: "changeme"

