---
- name: Pull Gluster Web Docker Image
  shell: |
    docker pull docker.io/like/gluster-web-interface
  register: pull_docker_image


- name: Run Gluster Web Docker Image
  shell: |
    docker run -it -p 3000:3000 docker.io/like/gluster-web-interface
  register: run_docker_image


- name: List Docker Processes
  shell: |
    docker ps
  register: list_docker_ps

