---
_volumes:
  - { name: "distvol01", devices: "/dev/vdb,/dev/vdc", brick: "/glusterfs/jbrick01,/glusterfs/jbrick02", perf_cache_size: "128MB", wb: "off", qr: "on", mount_dir: "/mnt/distvol01", fn: "fs-text01.txt", quota: "1GB", quota_dir: "/", quota_soft_limit: "70" }
  - { name: "distvol02", devices: "/dev/vdb,/dev/vdc", brick: "/glusterfs/jbrick11,/glusterfs/jbrick12", perf_cache_size: "128MB", wb: "off", qr: "on", mount_dir: "/mnt/distvol02", fn: "fs-text02.txt", quota: "1GB", quota_dir: "/", quota_soft_limit: "70" }
  - { name: "distvol03", devices: "/dev/vdb,/dev/vdc", brick: "/glusterfs/jbrick21,/glusterfs/jbrick22", perf_cache_size: "128MB", wb: "off", qr: "on", mount_dir: "/mnt/distvol03", fn: "fs-text03.txt", quota: "1GB", quota_dir: "/", quota_soft_limit: "70" }


_volume_count:
  replica: 3
  arbiter: 1
  disperse: 3
  redundant: 1

