---
- name: Detach Gluster Nodes
  shell: |
    echo y | gluster peer detach {{ item }}
  register: detach_nodes
  ignore_errors: true
  with_items: "{{ groups['append'] }}"
- debug: msg={{ detach_nodes }}


- name: Confirm Gluster Status
  shell: |
    gluster peer status
  register: confirm_status
  ignore_errors: true
- debug: msg={{ confirm_status }}


# gluster peer status
# Number of Peers: 1
#
# Hostname: co9-node02
# Uuid: 55f5178f-2da2-4a4d-ad7b-251a9bc6406f
# State: Peer in Cluster (Connected)
#
# echo y | gluster peer detach co9-node02
# All clients mounted through the peer which is getting detached need to be remounted using one of the other active peers in the trusted storage pool
# to ensure client gets notification on any changes done on the gluster configuration and if the same has been done do you want to proceed? (y/n) peer detach: success
# gluster peer status
# Number of Peers: 0

