---
- name: Purge Block Devices
  shell: |
    dd if=/dev/zero of={{ item.dev }} bs=1024 count=1000 conv=notrunc
  register: purge_block_devices
  ignore_errors: true
  with_items: "{{ _gluster.volumes }}"
- debug: msg={{ purge_block_devices }}
  when: print_debug == true


- name: Wipe Filesystem in Devices
  shell: |
    wipefs -a {{ item.dev }}
  register: wipefs_nvme_devices
  ignore_errors: true
  with_items: "{{ _gluster.volumes }}"
- debug: msg={{ wipefs_nvme_devices }}
  when: print_debug == true


- name: Delete Zap in Devices
  shell: |
    sgdisk --zap-all --delete {{ item.dev }}
  register: delete_zap_nvme_devices
  ignore_errors: true
  with_items: "{{ _gluster.volumes }}"
- debug: msg={{ delete_zap_nvme_devices }}
  when: print_debug == true


- name: Discard Block ID
  shell: |
    blkdiscard {{ item.dev }}
  register: discard_block_id
  ignore_errors: true
  with_items: "{{ _gluster.volumes }}"
- debug: msg={{ discard_block_id }}
  when: print_debug == true

