---
# path: "{{ item.brick }}"
#- name: Create Directory
#  file:
#    path: "/mnt/{{ item.name }}"
#    state: directory
#    owner: root
#    group: root
#    mode: 0755
#  register: create_dir
#  with_items: "{{ _volumes }}"
#- debug: msg={{ create_dir }}
#  when: print_debug == true


- name: Create Gluster Distribute Volumes
  import_tasks: volume/opts/create-distribute-volumes.yml
  when: ( distribute is defined and distribute == true )


- name: Create Gluster Replicate Volumes
  import_tasks: volume/opts/create-replicate-volumes.yml
  when: ( replicate is defined and replicate == true )


- name: Create Gluster Distribute/Replicate Volumes
  import_tasks: volume/opts/create-distribute-replicate-volumes.yml
  when: ( mixed is defined and mixed == true )


- name: Create Gluster Disperse Volumes
  import_tasks: volume/opts/create-disperse-volumes.yml
  when: ( disperse is defined and disperse == true )


- name: Start Gluster Volume
  gluster_volume:
    name: "{{ item.name }}"
    state: started
  register: start_volumes
  with_items: "{{ _volumes }}"
- debug: msg={{ start_volumes }}
# gluster volume start vol_distributed


- name: Confirm Gluster Volume Info
  shell: |
    gluster volume info
  register: confirm_volume_info
- debug: msg={{ confirm_volume_info }}



#######################################################################################
# Replicaation Mode
#######################################################################################
# Create volume
# $ gluster volume create vol_replica replica 3 transport tcp \
# node01:/glusterfs/replica \
# node02:/glusterfs/replica \
# node03:/glusterfs/replica
# volume create: vol_replica: success: please start the volume to access data


#######################################################################################
# Distributed Mode
#######################################################################################
# Create volume
# $ gluster volume create vol_distributed transport tcp \
# node01:/glusterfs/distributed \
# node02:/glusterfs/distributed
# volume create: vol_distributed: success: please start the volume to access data


#######################################################################################
# Distributed + Replication
#######################################################################################
# Create volume
# $ gluster volume create vol_dist-replica replica 3 arbiter 1 transport tcp \
# node01:/glusterfs/dist-replica \
# node02:/glusterfs/dist-replica \
# node03:/glusterfs/dist-replica \
# node04:/glusterfs/dist-replica \
# node05:/glusterfs/dist-replica \
# node06:/glusterfs/dist-replica
# volume create: vol_dist-replica: success: please start the volume to access data


#######################################################################################
# Dispersed Configuration
#######################################################################################
# Create volume
# $ gluster volume create vol_dispersed disperse-data 4 redundancy 2 transport tcp \
# node01:/glusterfs/dispersed \
# node02:/glusterfs/dispersed \
# node03:/glusterfs/dispersed \
# node04:/glusterfs/dispersed \
# node05:/glusterfs/dispersed \
# node06:/glusterfs/dispersed
# volume create: vol_dispersed: success: please start the volume to access data

