---
- name: Stop Gluster Volume
  gluster_volume:
    name: "{{ item.name }}"
    state: stopped
  register: stop_volumes
  with_items: "{{ _volumes }}"
- debug: msg={{ stop_volumes }}
# echo y | gluster volume stop vol_distributed


- name: Confirm Gluster Volume Status
  shell: |
    gluster volume status {{ item.name }}
  register: confirm_volume_status
  until: "'not started' in confirm_volume_status.stderr"
  retries: 10
  delay: 10
  failed_when: "'is not started' not in confirm_volume_status.stderr"
  with_items: "{{ _volumes }}"
- debug: msg={{ confirm_volume_status }}


- name: Delete Gluster Volumes
  gluster_volume:
    name: "{{ item.name }}"
    state: absent
  register: delete_volumes
  with_items: "{{ _volumes }}"
- debug: msg={{ delete_volumes }}
# echo y | gluster volume delete vol_distributed


- name: Confirm Gluster Volume Status
  shell: |
    gluster volume status {{ item.name }}
  register: confirm_volume_status
  until: "'does not exist' in confirm_volume_status.stderr"
  retries: 10
  delay: 10
  failed_when: "'does not exist' not in confirm_volume_status.stderr"
  with_items: "{{ _volumes }}"
- debug: msg={{ confirm_volume_status }}


#  path: "{{ item.brick }}"
- name: Delete Directory
  file:
    path: "/mnt/{{ item.name }}"
    state: absent
  register: delete_dir
  with_items: "{{ _volumes }}"
- debug: msg={{ delete_dir }}
  when: print_debug == true

