---
#- name: List Gluster Volumns Quota
#  shell: |
#    gluster volume quota {{ item.name }} list
#  register: list_gluster_volumes_quota
#  ignore_errors: true
#  with_items: "{{ _volumes }}"
#- debug: msg={{ list_gluster_volumes_quota }}
#  ignore_errors: true


- name: Remove Gluster Volumns Quota for Root Directory
  shell: |
    gluster volume quota {{ item.name }} remove /
  register: remove_gluster_volumes_root_dir_quota
  with_items: "{{ _volumes }}"
- debug: msg={{ remove_gluster_volumes_root_dir_quota }}


- name: Disable Gluster Volumns Quota
  shell: |
    echo y | gluster volume quota {{ item.name }} disable
  register: enable_gluster_volumes_quota
  with_items: "{{ _volumes }}"
- debug: msg={{ enable_gluster_volumes_quota }}


- name: Display Gluster Volumns Quota Info
  shell: |
    gluster volume info
  register: display_gluster_volumes_quota_info
- debug: msg={{ display_gluster_volumes_quota_info }}

