---
- name: Enable Gluster Volumns Quota
  shell: |
    gluster volume quota {{ item.name }} enable
  register: enable_gluster_volumes_quota
  with_items: "{{ _volumes }}"
- debug: msg={{ enable_gluster_volumes_quota }}


- name: Display Gluster Volumns Quota Info
  shell: |
    gluster volume info
  register: display_gluster_volumes_quota_info
- debug: msg={{ display_gluster_volumes_quota_info }}


- name: Set Gluster Volumns Quota
  shell: |
    gluster volume quota {{ item.name }} limit-usage / {{ item.quota }}
  register: set_gluster_volumes_quota
  with_items: "{{ _volumes }}"
- debug: msg={{ set_gluster_volumes_quota }}


#- name: List Gluster Volumns Quota
#  shell: |
#    gluster volume quota {{ item.name }} list
#  register: list_gluster_volumes_quota
#  with_items: "{{ _volumes }}"
#- debug: msg={{ list_gluster_volumes_quota }}

