---
- name: Rollback Repository Configurations File
  replace:
    path: "/etc/yum.repos.d/CentOS-{{ item.fn }}.repo"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
    backup: "{{ item.backup }}"
  register: rollback_required_config
  with_items:
    - { fn: "Samba-421",           regexp: "enabled=1",  line: "enabled=0",  backup: no }
  # when: ansible_os_family == 'Rocky' and ansible_distribution_major_version|int == 9


- name: Disable Gluster Samba Repository
  shell: |
    dnf config-manager --disable "centos-samba421"
  register: disable_gluster_repo
- debug: msg={{ disable_gluster_repo }}
  when: print_debug == true


- name: Uninstall Gluster NFS Ganesha Package Repository
  package:
    name: "{{ item }}"
    state: absent
  register: uninstall_repo_pkgs
  with_items:
    - "centos-release-samba421"


- name: Update Caches for DNF Packages
  shell: |
    dnf makecache -y
  register: update_dnf_cache

