---
- name: Uninstall Packages
  package:
    name: "{{ item }}"
    state: absent
  register: uninstall_pkgs
  with_items:
    - "samba"
    - "ctdb"
    - "samba-vfs-glusterfs"
    - "samba-*"
- debug: msg={{ uninstall_pkgs }}

