---
- name: Check OS ( Gluster )
  fail: msg="Not a Red Hat or SuSE based system!"
  when: ansible_os_family != 'RedHat' or  ansible_os_family != 'CentOS' or  ansible_os_family != 'Rocky'


- name: Set Facts For Network and Packages Informations
  import_tasks: set-ovirt-facts.yml
  tags: install, uninstall, deploy, destory, setup, remove, enable, disable, create, delete, add


- name: Import Repository and Packages Playbook
  import_tasks: pkgs/main.yml
  when: ( repo is defined and repo == true ) or ( pkgs is defined and pkgs == true )


- name: Import Gluster Server Playbook
  import_tasks: server/main.yml
  when: ( server is defined and server == true )


- name: Create GlusterFS Volumes
  import_tasks: create-volumes.yml
  tags: create
  when: ( volume is defined and volume == true ) and inventory_hostname in groups['control']


- name: Delete GlusterFS Volumes
  import_tasks: delete-volumes.yml
  tags: delete
  when: ( volume is defined and volume == true ) and inventory_hostname in groups['control']


- name: Import Gluster Clients Playbook
  import_tasks: client/main.yml
  when: ( client is defined and client == true )


#- name: Setup NTP Service
#  import_tasks: ext/setup-chrony.yml
#  tags: setup, install
#  when: ( ntp is defined and ntp == true )

