---
tcp_ports:
  # - 22
  - 80
  # For Gluster.
  - 111
  # Port-mapper for Gluster 3.4+.
  # - 2049
  # Gluster Daemon.
  - 24007
  # 24009+ for Gluster <= 3.3; 49152+ for Gluster 3.4+ (one port per server).
  - 24009
  - 24010
  - 24011
  # Gluster inline NFS server.
  - 38465
  - 38466
  - 38467

udp_ports:
  - 111

