---
- name: Confirm CTDB Status
  shell: |
    ctdb status
  register: confirm_ctdb_status
  ignore_errors: true
- debug: msg={{ confirm_ctdb_status }}
  when: print_debug == true


- name: Confirm CTDB IP
  shell: |
    ctdb ip
  register: confirm_ctdb_ip
  ignore_errors: true
- debug: msg={{ confirm_ctdb_ip }}
  when: print_debug == true


- name: Stop CTDB Services
  systemd:
    name: "{{ item.service }}"
    state: "{{ item.state }}"
    enabled: no
    daemon_reload: true
  register: stop_service
  ignore_errors: true
  until: stop_service is succeeded
  retries: 10
  delay: 10
  with_items:
    - { service: ctdb, state: stopped }
- debug: msg={{ stop_service }}
  when: print_debug == true


- name: Delete CTDB Config File
  file:
    path: "/etc/ctdb/{{ item }}"
    state: absent
  register: delete_ctdb_conf
  ignore_errors: true
  with_items:
    - "nodes"
    - "public_addresses"
- debug: msg={{ delete_ctdb_conf }}

