---
- name: Create Directory for Samba Mount
  file:
    path: "{{ item.mount_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0777
    recurse: yes
  register: create_smb_dir
  with_items: "{{ _volumes }}"
- debug: msg={{ create_smb_dir }}
  when: print_debug == true


- name: Mount Ephemeral GlusterFS Volume
  mount:
    src: "{{ hostvars[inventory_hostname].ansible_hostname }}:/{{ item.name }}"
    path: "{{ item.mount_dir }}"
    opts: ""
    fstype: glusterfs
    state: ephemeral
  register: mount_glusterfs_dir
  with_items: "{{ _volumes }}"
- debug: msg={{ mount_glusterfs_dir }}
  when: print_debug == true


- name: Delete Directory Mounted
  file:
    path: "{{ item.mount_dir }}/{{ item.smbshare }}"
    state: absent
  register: delete_smb_share_dir
  with_items: "{{ _volumes }}"
- debug: msg={{ delete_smb_share_dir }}
  when: print_debug == true


- name: Umount Directory Mounted
  shell: |
    umount {{ item.mount_dir }}
  register: unmount_dir
  with_items: "{{ _volumes }}"
- debug: msg={{ unmount_dir }}
  when: print_debug == true


- name: Delete OS User
  user:
    name: "{{ _smb.user }}"
    state: absent
    remove: yes
  register: delete_os_user
- debug: msg={{ delete_os_user }}
  when: print_debug == true


# name: smbshare
- name: Delete OS Group
  group:
    name: "{{ _smb.group }}"
    state: absent
  register: delete_os_group
- debug: msg={{ delete_os_group }}
  when: print_debug == true

