---
- name: Check OS ( Gluster NFS Ganesha )
  fail: msg="Not a Red Hat or SuSE based system!"
  when: ansible_os_family != 'RedHat' or  ansible_os_family != 'CentOS' or  ansible_os_family != 'Rocky'


- name: Set Facts For Network and Packages Informations
  import_tasks: set-ganesha-facts.yml
  tags: install, uninstall, deploy, destory, setup, remove, enable, disable, create, delete, add, start, stop


- name: Import Repository and Packages Playbook
  import_tasks: pkgs/main.yml
  when: ( repo is defined and repo == true ) or ( pkgs is defined and pkgs == true )


- name: Import Gluster NFS Ganesha Playbook
  import_tasks: server/main.yml
  when: ( server is defined and server == true )


- name: Import Gluster Clients Playbook
  import_tasks: client/main.yml
  when: ( client is defined and client == true )

