---
- name: Setup GlusterFS Clients
  import_tasks: client/setup-clients.yml
  tags: setup, install
  when: ( samba is defined and samba == true ) and inventory_hostname in groups['clients']


- name: Remove GlusterFS Clients
  import_tasks: client/remove-clients.yml
  tags: remove, uninstall
  when: ( samba is defined and samba == true ) and inventory_hostname in groups['clients']

