---
- name: Delete Text File
  file:
    path: "{{ item.mount_dir }}/{{ item.fn }}"
    state: absent
  register: delete_text_files
  with_items: "{{ _volumes }}"
- debug: msg={{ delete_text_files }}
  when: print_debug == true


- name: Umount Gluster NFS Directory
  mount:
    path: "{{ item.mount_dir }}"
    state: unmounted
  register: umount_nfs_dir
  with_items: "{{ _volumes }}"
- debug: msg={{ umount_nfs_dir }}
  when: print_debug == true
# umount -f -l {{ item.mount_dir }}


- name: Delete Directory Mounted with Gluster NFS
  file:
    path: "{{ item.mount_dir }}"
    state: absent
  register: delete_nfs_dir
  with_items: "{{ _volumes }}"
- debug: msg={{ delete_nfs_dir }}
  when: print_debug == true


- name: Uninstall NFS Client Packages
  package: name={{ item }} state=absent
  with_items:
    - "nfs-utils"
  register: uninstall_nfs_pkgs
- debug: msg={{ uninstall_nfs_pkgs }}
  when: print_debug == true

