---
- name: Delete Text File
  file:
    path: "{{ item.mount_dir }}/{{ item.fn }}"
    state: absent
  register: delete_text_files
  with_items: "{{ _volumes }}"
- debug: msg={{ delete_text_files }}
  when: print_debug == true


- name: Umount Gluster Samba Directory
  mount:
    path: "{{ item.mount_dir }}"
    state: unmounted
  register: umount_samba_dir
  with_items: "{{ _volumes }}"
- debug: msg={{ umount_samba_dir }}
  when: print_debug == true
# umount -f -l {{ item.mount_dir }}


- name: Delete Directory Mounted with Gluster Samba
  file:
    path: "{{ item.mount_dir }}"
    state: absent
  register: delete_samba_dir
  with_items: "{{ _volumes }}"
- debug: msg={{ delete_samba_dir }}
  when: print_debug == true


- name: Uninstall Samba Client Packages
  package: name={{ item }} state=absent
  with_items:
    - "samba-client"
  register: uninstall_samba_client_pkgs
- debug: msg={{ uninstall_samba_client_pkgs }}
  when: print_debug == true

