---
- name: Create Gluster Replicate Volumes
  gluster_volume:
    name: "{{ item.name }}"
    state: present
    bricks: "{{ item.brick }}"
    rebalance: yes
    replicas: "{{ _volume_count.replica }}"
    cluster: "{{ groups['workers'] }}"
    force: yes
    options:
      { performance.cache-size: "{{ item.perf_cache_size }}",
        write-behind: "{{ item.wb }}",
        quick-read: "{{ item.qr }}"
      }
  with_items: "{{ _volumes }}"


- name: Start Gluster Volume
  gluster_volume:
    name: "{{ item.name }}"
    state: started
  register: start_volumes
  with_items: "{{ _volumes }}"
- debug: msg={{ start_volumes }}


- name: Confirm Gluster Volume Info
  shell: |
    gluster volume info
  register: confirm_volume_info
- debug: msg={{ confirm_volume_info }}

