---
- name: Create Gluster Distribute Volumes
  gluster_volume:
    name: "{{ item.name }}"
    state: present
    force: true
    bricks: "{{ item.brick }}"
    rebalance: yes
    cluster: "{{ groups['workers'] }}"
    options:
      { performance.cache-size: "{{ item.perf_cache_size }}",
        write-behind: "{{ item.wb }}",
        quick-read: "{{ item.qr }}"
      }
  with_items: "{{ _volumes }}"

