---
- name: Rollback Repository Configurations File
  replace:
    path: "/etc/yum.repos.d/CentOS-{{ item.fn }}.repo"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
    backup: "{{ item.backup }}"
  register: rollback_required_config
  with_items:
    - { fn: "Gluster-{{ _gluster.major_version }}",           regexp: "enabled=0",  line: "enabled=1",  backup: no }
  # when: ansible_os_family == 'Rocky' and ansible_distribution_major_version|int == 9


- name: Disable Gluster Server Repository
  shell: |
    dnf config-manager --disable "centos-gluster{{ _gluster.major_version }}"
  register: disable_gluster_repo
- debug: msg={{ disable_gluster_repo }}
  when: print_debug == true


- name: Uninstall Gluster Package Repository
  package:
    name: "{{ item }}"
    state: absent
  register: uninstall_repo_pkgs
  with_items:
    - "centos-release-gluster{{ _gluster.major_version }}"


- name: Update Caches for DNF Packages
  shell: |
    dnf makecache -y
  register: update_dnf_cache

