---
- name: Uninstall Packages
  package:
    name: "{{ item }}"
    state: absent
  register: uninstall_pkgs
  ignore_errors: true
  with_items:
    - glusterfs-server
    - glusterfs-*
    - libglusterfs0

