---

# https://docs.redhat.com/ko/documentation/red_hat_enterprise_linux/7/html/selinux_users_and_administrators_guide/sect-managing_confined_services-glusterfs-configuration_examples#sect-Managing_Confined_Services-glusterFS-Configuration_Examples-Labeling_Gluster_Bricks

- name: Change SELinux Type
  shell: |
     for i in `echo {{ item.brick }} | sed -e 's/,/ /g'`
     do
       semanage fcontext -a -t glusterd_brick_t '$i(/.*)?'
     done
  register: change_selinux_type
  with_items: "{{ _volumes }}"
- debug: msg={{ change_selinux_type }}
  when: print_debug == true


- name: Apply SELinux Type
  shell: |
     for j in `echo {{ item.brick }} | sed -e 's/,/ /g'`
     do
       restorecon -Rv $j
     done
  register: apply_selinux_type
  with_items: "{{ _volumes }}"
- debug: msg={{ apply_selinux_type }}
  when: print_debug == true


# Check SELinux Context
# ls -lZd /mnt/brick1/

