---
- name: Start Gluster NFS Ganesha
  import_tasks: server/start-nfs-ganesha.yml
  tags: start, enable, install
  when: inventory_hostname in groups['workers']


- name: Stop Gluster NFS Ganesha
  import_tasks: server/stop-nfs-ganesha.yml
  tags: stop, disable, uninstall
  when: inventory_hostname in groups['workers']

