---
- name: Install NFS Client Packages
  package: name={{item}} state=present
  with_items:
    - "nfs-utils"


- name: Create Directory to Mount NFS
  file:
    path: "/mnt/glusterfs02"
    state: directory
    owner: root
    group: root
    mode: 0777
    recurse: yes
  register: create_nfs_dir
- debug: msg={{ create_nfs_dir }}
  when: print_debug == true


- name: Mount Ephemeral NFS Volume
  mount:
    src: "co9-node01:/vfs_distributed"
    path: "/mnt/glusterfs02"
    opts: ""
    fstype: nfs4
    state: ephemeral
  register: mount_nfs_dir
- debug: msg={{ mount_nfs_dir }}
  when: print_debug == true


- name: Create a File with the Content
  copy:
    content: "Hellow Gluster NFS4 World!"
    dest: "/mnt/glusterfs02/test-nfs01.txt"
    force: no
    owner: root
    group: root
    mode: 0644


#- name: Mount network share
#  mount:
#    src: //path/to/windows/share
#    path: /mnt
#    fstype: cifs
#    opts: 'username=example@domain,password=Password1!'
#    state: mounted
#  become: true


#- name: Unmount network share
#  mount:
#    path: /mnt
#    state: absent
#  become: true


